# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'try-anything' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for try-anything
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'try-anythingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'try-anythingUITests' do
    # Pods for testing
  end

end
